import api from '../api/axios'

const REPORT_META = {
  company_placements: {
    subtitle: 'Company / Position Placement Report',
    slug: 'company-placements',
  },
  student_placements: {
    subtitle: 'Student Placement Report',
    slug: 'student-placements',
  },
  placement_history: {
    subtitle: 'Placement History Report',
    slug: 'placement-history',
  },
}

const STATUS_LABELS = {
  suggested: 'Suggested',
  approved: 'Approved',
  removed: 'Removed',
  rejected: 'Rejected',
}

const FILTER_LABELS = {
  status: 'Status',
  company_id: 'Company',
  position_id: 'Position',
  batch_id: 'Batch',
  course: 'Course',
  area: 'Area',
  date_field: 'Date field',
  date_from: 'From',
  date_to: 'To',
}

const clean = value => value == null || value === '' ? '—' : String(value)
const percent = value => value == null ? '—' : `${Number(value).toFixed(1)}%`
const distance = value => value == null ? '—' : `${Number(value).toFixed(1)} km`
const person = value => value?.name || '—'

function dateTime(value) {
  if (!value) return '—'
  return new Intl.DateTimeFormat('en-PH', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(value))
}

function reportDate() {
  const parts = new Intl.DateTimeFormat('en-CA', {
    year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(new Date())
  const values = Object.fromEntries(parts.map(part => [part.type, part.value]))
  return `${values.year}-${values.month}-${values.day}`
}

function filterDescription(payload, labels = {}) {
  const values = []
  Object.entries(payload.filters || {}).forEach(([key, value]) => {
    if (!FILTER_LABELS[key] || value == null || value === '' || value === 'all') return
    let display = labels[key]?.[value] || value
    if (key === 'date_field') display = value === 'approved_at' ? 'Approved date' : 'Created date'
    values.push(`${FILTER_LABELS[key]}: ${display}`)
  })
  return values.length ? values.join('  |  ') : 'No filters (all placement records)'
}

function drawReportHeader(doc, payload, filterLabels) {
  const width = doc.internal.pageSize.getWidth()
  doc.setFillColor(20, 83, 45)
  doc.rect(0, 0, width, 27, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('SkillBridge OJT Placement Report', 12, 11)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(REPORT_META[payload.report_type].subtitle, 12, 19)
  doc.setFontSize(7.5)
  doc.text(`Generated: ${dateTime(payload.generated_at)}`, width - 12, 10, { align: 'right' })
  doc.text(`Generated by: ${person(payload.generated_by)} (${clean(payload.generated_by?.role)})`, width - 12, 17, { align: 'right' })

  doc.setTextColor(55, 65, 81)
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'bold')
  doc.text('FILTERS USED', 12, 34)
  doc.setFont('helvetica', 'normal')
  const filterLines = doc.splitTextToSize(filterDescription(payload, filterLabels), width - 24)
  doc.text(filterLines, 12, 39)

  const summaryY = 43 + (filterLines.length * 3)
  const summaryItems = [
    ['Records', payload.summary.total_records],
    ['Students', payload.summary.unique_students],
    ['Companies', payload.summary.unique_companies],
    ['Positions', payload.summary.unique_positions],
    ['Approved', payload.summary.status_counts.approved],
    ['Remaining slots', payload.summary.remaining_slots],
  ]
  const gap = 2
  const boxWidth = (width - 24 - gap * (summaryItems.length - 1)) / summaryItems.length
  summaryItems.forEach(([label, value], index) => {
    const x = 12 + index * (boxWidth + gap)
    doc.setFillColor(242, 247, 244)
    doc.roundedRect(x, summaryY, boxWidth, 14, 1.5, 1.5, 'F')
    doc.setTextColor(20, 83, 45)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text(clean(value), x + 3, summaryY + 6)
    doc.setTextColor(75, 85, 99)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.text(label, x + 3, summaryY + 11)
  })
  return summaryY + 21
}

function tableTheme(overrides = {}) {
  return {
    theme: 'grid',
    margin: { left: 12, right: 12, bottom: 16 },
    styles: {
      font: 'helvetica', fontSize: 6.4, cellPadding: 1.7,
      overflow: 'linebreak', valign: 'middle', textColor: [55, 65, 81],
    },
    headStyles: {
      fillColor: [31, 41, 55], textColor: [255, 255, 255],
      fontStyle: 'bold', fontSize: 6.5,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    ...overrides,
  }
}

function addCompanyTables(doc, autoTable, records, startY) {
  const groups = new Map()
  records.forEach(record => {
    const key = `${record.company.id}:${record.position.id}`
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key).push(record)
  })
  let y = startY
  if (!groups.size) {
    autoTable(doc, tableTheme({
      startY: y,
      head: [['Company / Position', 'Placement records']],
      body: [['—', 'No placement records match the selected filters.']],
    }))
    return
  }
  groups.forEach(group => {
    const first = group[0]
    if (y > doc.internal.pageSize.getHeight() - 42) {
      doc.addPage()
      y = 18
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(20, 83, 45)
    doc.text(`${first.company.name} — ${first.position.title}`, 12, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(75, 85, 99)
    const capacity = `${first.position.approved_count} approved / ${first.position.slots_available} slots / ${first.position.remaining_slots} remaining`
    doc.text(`${first.company.address_text || 'Address not provided'}  |  ${capacity}`, 12, y + 5)
    autoTable(doc, tableTheme({
      startY: y + 8,
      head: [[
        'Student', 'School ID', 'Course', 'Batch', 'Status', 'Hybrid match',
        'Category fit', 'NLP fit', 'Location fit', 'Distance', 'Approved at', 'Remarks',
      ]],
      body: group.map(record => [
        record.student.name,
        clean(record.student.school_id),
        clean(record.student.course),
        clean(record.batch?.name),
        STATUS_LABELS[record.status] || record.status,
        percent(record.match_score_at_assignment),
        percent(record.category_score_component_at_assignment),
        percent(record.nlp_score_component_at_assignment),
        percent(record.location_score_component_at_assignment),
        distance(record.distance_km_at_assignment),
        dateTime(record.approved_at),
        clean(record.remarks),
      ]),
      columnStyles: {
        0: { cellWidth: 28 }, 1: { cellWidth: 16 }, 2: { cellWidth: 15 },
        3: { cellWidth: 21 }, 4: { cellWidth: 16 }, 5: { cellWidth: 14 },
        6: { cellWidth: 14 }, 7: { cellWidth: 14 }, 8: { cellWidth: 14 },
        9: { cellWidth: 16 }, 10: { cellWidth: 27 }, 11: { cellWidth: 'auto' },
      },
    }))
    y = doc.lastAutoTable.finalY + 11
  })
}

function addStudentTable(doc, autoTable, records, startY) {
  autoTable(doc, tableTheme({
    startY,
    head: [[
      'Student', 'School ID', 'Email', 'Course', 'Batch', 'Company', 'Position',
      'Status', 'Match', 'Distance', 'Approved at', 'Remarks',
    ]],
    body: records.length ? records.map(record => [
      record.student.name,
      clean(record.student.school_id),
      clean(record.student.email),
      clean(record.student.course),
      clean(record.batch?.name),
      record.company.name,
      record.position.title,
      STATUS_LABELS[record.status] || record.status,
      percent(record.match_score_at_assignment),
      distance(record.distance_km_at_assignment),
      dateTime(record.approved_at),
      clean(record.remarks),
    ]) : [['No placement records match the selected filters.']],
    columnStyles: {
      0: { cellWidth: 25 }, 1: { cellWidth: 16 }, 2: { cellWidth: 34 },
      3: { cellWidth: 14 }, 4: { cellWidth: 20 }, 5: { cellWidth: 28 },
      6: { cellWidth: 25 }, 7: { cellWidth: 16 }, 8: { cellWidth: 14 },
      9: { cellWidth: 15 }, 10: { cellWidth: 26 }, 11: { cellWidth: 'auto' },
    },
  }))
}

function addHistoryTable(doc, autoTable, records, startY) {
  autoTable(doc, tableTheme({
    startY,
    styles: { font: 'helvetica', fontSize: 6.1, cellPadding: 1.6, overflow: 'linebreak', valign: 'top', textColor: [55, 65, 81] },
    head: [['ID', 'Student', 'Placement', 'Status', 'Decision actors', 'Timeline', 'Score snapshot', 'Remarks']],
    body: records.length ? records.map(record => [
      record.id,
      `${record.student.name}\n${clean(record.student.school_id)} | ${clean(record.student.course)}\n${clean(record.batch?.name)}`,
      `${record.position.title}\n${record.company.name}`,
      STATUS_LABELS[record.status] || record.status,
      `Assigned: ${person(record.assigned_by)}\nApproved: ${person(record.approved_by)}\nRemoved: ${person(record.removed_by)}\nRejected: ${person(record.rejected_by)}`,
      `Created: ${dateTime(record.created_at)}\nUpdated: ${dateTime(record.updated_at)}\nApproved: ${dateTime(record.approved_at)}\nRemoved: ${dateTime(record.removed_at)}\nRejected: ${dateTime(record.rejected_at)}`,
      `Hybrid match: ${percent(record.match_score_at_assignment)}\nCategory fit: ${percent(record.category_score_component_at_assignment)}\nNLP fit: ${percent(record.nlp_score_component_at_assignment)}\nLocation fit: ${percent(record.location_score_component_at_assignment)}\nDistance: ${distance(record.distance_km_at_assignment)}`,
      clean(record.remarks),
    ]) : [['—', 'No placement records match the selected filters.']],
    columnStyles: {
      0: { cellWidth: 10 }, 1: { cellWidth: 34 }, 2: { cellWidth: 36 },
      3: { cellWidth: 17 }, 4: { cellWidth: 40 }, 5: { cellWidth: 52 },
      6: { cellWidth: 38 }, 7: { cellWidth: 'auto' },
    },
  }))
}

function addSignaturesAndFooters(doc) {
  const height = doc.internal.pageSize.getHeight()
  const width = doc.internal.pageSize.getWidth()
  let y = (doc.lastAutoTable?.finalY || 50) + 23
  if (y > height - 30) {
    doc.addPage()
    y = 28
  }
  const labels = ['Prepared by', 'Checked by', 'Approved by']
  const sectionWidth = (width - 34) / 3
  labels.forEach((label, index) => {
    const x = 12 + index * (sectionWidth + 5)
    doc.setDrawColor(107, 114, 128)
    doc.line(x, y, x + sectionWidth, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(75, 85, 99)
    doc.text(label, x + sectionWidth / 2, y + 5, { align: 'center' })
  })

  const pages = doc.getNumberOfPages()
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(107, 114, 128)
    doc.text('SkillBridge — Official OJT placement record', 12, height - 7)
    doc.text(`Page ${page} of ${pages}`, width - 12, height - 7, { align: 'right' })
  }
}

export async function fetchPlacementReport(filters) {
  const params = new URLSearchParams()
  Object.entries(filters).forEach(([key, value]) => {
    if (value != null && value !== '') params.set(key, value)
  })
  const response = await api.get(`/api/placements/reports/?${params.toString()}`)
  return response.data
}

export async function downloadPlacementPdf(payload, filterLabels = {}) {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const autoTable = autoTableModule.default
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const startY = drawReportHeader(doc, payload, filterLabels)
  if (payload.report_type === 'company_placements') {
    addCompanyTables(doc, autoTable, payload.records, startY)
  } else if (payload.report_type === 'student_placements') {
    addStudentTable(doc, autoTable, payload.records, startY)
  } else {
    addHistoryTable(doc, autoTable, payload.records, startY)
  }
  addSignaturesAndFooters(doc)
  doc.save(`skillbridge-${REPORT_META[payload.report_type].slug}-${reportDate()}.pdf`)
}

function spreadsheetRows(payload) {
  return payload.records.map(record => ({
    'Placement ID': record.id,
    'Student Name': record.student.name,
    'School ID': record.student.school_id,
    Email: record.student.email,
    Course: record.student.course,
    Batch: record.batch?.name || '',
    Company: record.company.name,
    'Company Address': record.company.address_text,
    Position: record.position.title,
    'Slots Available': record.position.slots_available,
    'Approved Count': record.position.approved_count,
    'Remaining Slots': record.position.remaining_slots,
    Status: STATUS_LABELS[record.status] || record.status,
    'Hybrid match': record.match_score_at_assignment,
    'Category fit': record.category_score_component_at_assignment,
    'NLP fit': record.nlp_score_component_at_assignment,
    'Location fit': record.location_score_component_at_assignment,
    'Distance (km)': record.distance_km_at_assignment,
    'Assigned By': person(record.assigned_by),
    'Approved By': person(record.approved_by),
    'Removed By': person(record.removed_by),
    'Rejected By': person(record.rejected_by),
    'Created At': dateTime(record.created_at),
    'Updated At': dateTime(record.updated_at),
    'Approved At': dateTime(record.approved_at),
    'Removed At': dateTime(record.removed_at),
    'Rejected At': dateTime(record.rejected_at),
    Remarks: record.remarks,
  }))
}

export async function downloadPlacementXlsx(payload) {
  const XLSX = await import('xlsx')
  const rows = spreadsheetRows(payload)
  const fallbackHeader = Object.keys(spreadsheetRows({ records: [{
    id: '', student: {}, batch: null, company: {}, position: {}, assigned_by: null,
    approved_by: null, removed_by: null, rejected_by: null,
  }] })[0])
  const worksheet = rows.length
    ? XLSX.utils.json_to_sheet(rows)
    : XLSX.utils.aoa_to_sheet([fallbackHeader])
  worksheet['!cols'] = fallbackHeader.map(header => ({
    wch: Math.min(Math.max(header.length + 2, 14), 34),
  }))
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Placements')
  XLSX.writeFile(workbook, `skillbridge-${REPORT_META[payload.report_type].slug}-${reportDate()}.xlsx`)
}

export { REPORT_META }
