# Generated by Django 6.0.4 on 2026-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
