# Generated by Django 6.0.4 on 2026-04-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_employee_id_user_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseanswer',
            name='text_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False'), ('identification', 'Identification')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.answerchoice'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
