# Generated by Django 6.0.4 on 2026-05-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_responseanswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'position')},
        ),
    ]
