# Generated by Django 6.0.4 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recommendation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='question_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
