# Generated by Django 6.0.4 on 2026-09-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentresponse_integrity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='position',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='category_score_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='location_score_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='nlp_score_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='RecommendationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_model', models.CharField(choices=[('spacy_sm', 'spaCy Small (en_core_web_sm)'), ('spacy_md', 'spaCy Medium (en_core_web_md)'), ('stanza_en', 'Stanza English')], default='spacy_md', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
