# Generated by Django 6.0.4 on 2026-09-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hybrid_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompetencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation_label', models.CharField(blank=True, default='', max_length=160)),
                ('orientation_summary', models.TextField(blank=True, default='')),
                ('competency_profile_text', models.TextField(blank=True, default='')),
                ('development_suggestions', models.JSONField(blank=True, default=list)),
                ('supporting_categories', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_profiles', to='api.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
