# Generated by Django 6.0.4 on 2026-09-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_competency_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score_at_assignment', models.FloatField(blank=True, null=True)),
                ('category_score_component_at_assignment', models.FloatField(blank=True, null=True)),
                ('nlp_score_component_at_assignment', models.FloatField(blank=True, null=True)),
                ('location_score_component_at_assignment', models.FloatField(blank=True, null=True)),
                ('distance_km_at_assignment', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('removed', 'Removed'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_placements_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_placements', to='api.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ojt_placements', to='api.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ojt_placements', to='api.position')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_placements', to='api.recommendation')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_placements_rejected', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_placements_removed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ojt_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['position', 'status'], name='ojt_pos_status_idx'), models.Index(fields=['student', 'status'], name='ojt_student_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('student',), name='unique_approved_placement_per_student')],
            },
        ),
    ]
