# Generated by Django 6.0.4 on 2026-09-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_multiple_assessment_foundation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='api.batch'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'batch', 'position')},
        ),
        migrations.CreateModel(
            name='CombinedCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('source_assessment_ids', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_category_scores', to='api.batch')),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skillcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_category_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'batch', 'skill_category')},
            },
        ),
        migrations.CreateModel(
            name='CombinedCompetencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False)),
                ('included_assessment_ids', models.JSONField(blank=True, default=list)),
                ('orientation_label', models.CharField(blank=True, default='', max_length=160)),
                ('orientation_summary', models.TextField(blank=True, default='')),
                ('competency_profile_text', models.TextField(blank=True, default='')),
                ('development_suggestions', models.JSONField(blank=True, default=list)),
                ('supporting_categories', models.JSONField(blank=True, default=list)),
                ('text_generation_version', models.CharField(blank=True, default='', max_length=80)),
                ('active_model', models.CharField(blank=True, default='', max_length=40)),
                ('model_used', models.CharField(blank=True, default='', max_length=40)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_profiles', to='api.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttemptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_reason', models.CharField(blank=True, default='', max_length=50)),
                ('is_flagged', models.BooleanField(default=False)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('violation_events', models.JSONField(blank=True, default=list)),
                ('question_layout', models.JSONField(blank=True, default=dict)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('category_scores', models.JSONField(blank=True, default=list)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_attempts', to='api.studentresponse')),
            ],
            options={
                'unique_together': {('response', 'attempt_number')},
            },
        ),
    ]
